### ISSUE TITLE
sparsepp isn't c++98, therefore MiniDNN is also not c++98 compliant

### ISSUE THREAD

**Issue by yurivict** [yixuan/MiniDNN#13]
With -std=c++98 clang-8 complains:
```
MiniDNN/include/Optimizer/../external/sparsepp/spp_utils.h:147:9: error: no member named 'tr1' in namespace 'std'
        SPP_HASH_CLASS<T> hasher;
        ^~~~~~~~~~~~~~
MiniDNN/include/Optimizer/../external/sparsepp/spp_utils.h:88:36: note: expanded from macro 'SPP_HASH_CLASS'
       #define SPP_HASH_CLASS std::tr1::hash
                              ~~~~~^
MiniDNN/include/Optimizer/../external/sparsepp/spp_utils.h:147:24: error: 'T' does not refer to a value
        SPP_HASH_CLASS<T> hasher;
                       ^
MiniDNN/include/Optimizer/../external/sparsepp/spp_utils.h:142:17: note: declared here
template <class T>
                ^
MiniDNN/include/Optimizer/../external/sparsepp/spp_utils.h:147:27: error: use of undeclared identifier 'hasher'
        SPP_HASH_CLASS<T> hasher;
                          ^
```

So you might want to update the README with a correct level of C++ standard for MiniDNN.

**Comment by yixuan** [comment]
I have removed the dependence on sparsepp in the [development](https://github.com/yixuan/MiniDNN/tree/development) branch. I would appreciate if you could test again. Thanks.

**Comment by yurivict** [comment]
Somehow, 3493f175f06f2b595839d83dfb09290197ef8b7a still contains ```sparsepp```.

**Comment by yixuan** [comment]
Yes, I haven't removed the files for testing purpose. Once the PR #14 is merged I will delete `sparsepp` from the repository.

**Comment by yurivict** [comment]
My I ask, why do you make a point of supporting the old standard ```c++98```? Doesn't this make it more difficult to program, because newer C++ features like lambda functions aren't available in ```c++98```?

**Comment by yixuan** [comment]
No specific reasons. I was slowly learning C++ and C++98 was the start. The massive new features in C++11 was a bit overwhelming to me, but maybe I will shift to the new standard in my next C++ project.

**Comment by yurivict** [comment]
There are a lot of useful features in C++11 and C++17. I particularly find lambda functions useful because they allow to create local helper functions within other functions without polluting the namespace with names.
