### ISSUE TITLE
Compile error with GCC 8.3

### ISSUE THREAD

**Issue by SebDyn** [yixuan/MiniDNN#7]
With recent GCC I get a compiler warning (which is interpreted as an error in my project due to -Werror):
`
sparsepp.h:3881:27: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘spp::sparsetable<std::pair<const double* const, Eigen::Array<double, -1, 1> >, spp::libc_allocator_with_realloc<std::pair<const double* const, Eigen::Array<double, -1, 1> > > >::group_type’ {aka ‘class spp::sparsegroup<std::pair<const double* const, Eigen::Array<double, -1, 1> >, spp::libc_allocator_with_realloc<std::pair<const double* const, Eigen::Array<double, -1, 1> > > >’} with no trivial copy-assignment; use copy-initialization instead [-Werror=class-memaccess]
                     memcpy(first, _first_group, sizeof(*first) * (std::min)(sz, old_sz)); 
`

Do you have any idea to fix this ? I can compile it by deactivating the specific warning, but there is definitely an issue in the code...

**Comment by yixuan** [comment]
This should have been fixed.
